"""nuevos campos se agregarom

Revision ID: 3da6bfec1ce0
Revises: e2ed8e288d07
Create Date: 2023-06-03 00:07:08.037629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da6bfec1ce0'
down_revision = 'e2ed8e288d07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conserje', sa.Column('direccion', sa.String(length=60), nullable=True))
    op.add_column('conserje', sa.Column('telefono', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conserje', 'telefono')
    op.drop_column('conserje', 'direccion')
    # ### end Alembic commands ###
