"""changed Departamento

Revision ID: 962192dc967d
Revises: a2301ac4c26d
Create Date: 2023-06-08 12:28:22.645200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962192dc967d'
down_revision = 'a2301ac4c26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departamento', sa.Column('foto', sa.LargeBinary(length=4294967295), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departamento', 'foto')
    # ### end Alembic commands ###
