"""new table copropietario

Revision ID: a2301ac4c26d
Revises: 3da6bfec1ce0
Create Date: 2023-06-03 10:27:57.764466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2301ac4c26d'
down_revision = '3da6bfec1ce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copropietario',
    sa.Column('id_user', sa.String(length=4), nullable=False),
    sa.Column('carnet', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=60), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('id_departamento', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copropietario')
    # ### end Alembic commands ###
