"""db

Revision ID: ad1073f8aea2
Revises: 
Create Date: 2023-05-27 23:39:53.684403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1073f8aea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id_permission', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_permission')
    )
    op.create_table('role',
    sa.Column('id_role', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('role_permission',
    sa.Column('id_role_permission', sa.String(length=4), nullable=False),
    sa.Column('id_role', sa.String(length=4), nullable=True),
    sa.Column('id_permission', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_permission'], ['permission.id_permission'], ),
    sa.ForeignKeyConstraint(['id_role'], ['role.id_role'], ),
    sa.PrimaryKeyConstraint('id_role_permission')
    )
    op.create_table('user',
    sa.Column('id_user', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.id_role'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('administrator',
    sa.Column('id_user', sa.String(length=4), nullable=False),
    sa.Column('address', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('conserje',
    sa.Column('id_user', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('user_permission',
    sa.Column('id_user_permission', sa.String(length=4), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('id_permission', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['id_permission'], ['permission.id_permission'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_permission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission')
    op.drop_table('conserje')
    op.drop_table('administrator')
    op.drop_table('user')
    op.drop_table('role_permission')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
