"""db conserje

Revision ID: e2ed8e288d07
Revises: 6b7c5c8afd5a
Create Date: 2023-05-28 10:51:50.913809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ed8e288d07'
down_revision = '6b7c5c8afd5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conserje', sa.Column('cargo', sa.String(length=20), nullable=False))
    op.add_column('conserje', sa.Column('carnet', sa.String(length=10), nullable=False))
    op.add_column('conserje', sa.Column('antecedentes', sa.String(length=50), nullable=False))
    op.add_column('conserje', sa.Column('foto', sa.LargeBinary(length=4294967295), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conserje', 'foto')
    op.drop_column('conserje', 'antecedentes')
    op.drop_column('conserje', 'carnet')
    op.drop_column('conserje', 'cargo')
    # ### end Alembic commands ###
