version: "3"
networks:
  parking-system-net:

services:
  parking-system:
    build:
      context: .
    networks:
      parking-system-net:
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - .:/workspace
